const path = require('path');
const webpack = require('webpack');
const FavIconsWebpackPlugin = require('favicons-webpack-plugin');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const WorkboxWebpackPlugin = require('workbox-webpack-plugin');
const {CleanWebpackPlugin} = require('clean-webpack-plugin');

module.exports = {
  entry: path.join(__dirname, 'src', 'client', 'index.js'),
  mode: 'production',
  stats: 'none',
  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: '[name].[chunkhash].bundle.js',
    path: path.join(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: '/\.js$/',
        exclude: /node_modules/,
        loader: ['babel-loader', 'eslint-loader'],
      }, {
        // Apply rule for .sass, .scss or .css files
        test: /\.(sa|sc|c)ss$/,
        exclude: /node_modules/,
        // Set loaders to transform files.
        // Loaders are applying from right to left(!)
        // The first loader will be applied after others
        use: [
          {
            // Creates "style" nodes from JS strings
            loader: 'style-loader',
          }, {
            // This loader resolves url() and @imports inside CSS
            loader: 'css-loader',
          }, {
            // First we transform SASS to standard CSS
            loader: 'sass-loader',
            options: {
              implementation: require('sass'),
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new CleanWebpackPlugin({
      // Simulate the removal of files
      dry: true,
      // Write Logs to Console
      verbose: true,
      // Automatically remove all unused webpack assets on rebuild
      cleanStaleWebpackAssets: true,
      protectWebpackAssets: false,
    }),
    new webpack.HashedModuleIdsPlugin(),
    new HtmlWebPackPlugin({
      title: 'YouTravel',
      template: './src/client/views/index.html',
      minify: {
        collapseWhitespace: true,
        removeComments: true,
      },
      filename: './index.html',
    }),
    new FavIconsWebpackPlugin({
      // Your source logo (required)
      logo: './src/client/assets/favicon/logo.png',
      mode: 'webapp',
      devMode: 'webapp',
      // Enable caching and optionally specify the path to store cached data
      // Note: disabling caching may increase build times considerably
      cache: true,
      // Override the publicPath option usually read from webpack configuration
      publicPath: './',
      // The directory to output the assets relative to the webpack output dir.
      // Relative string paths are allowed here ie '../public/static'. If this
      // option is not set, `prefix` is used.
      outputPath: './',
      // Prefix path for generated assets
      prefix: 'assets/favicon',
      // Inject html links/metadata (requires html-webpack-plugin).
      // This option accepts arguments of different types:
      //  * boolean
      //    `false`: disables injection
      //    `true`: enables injection if that is not disabled in html-webpack-plugin
      //  * string
      //    `'force'`: enables injection even if that is disabled in html-webpack-plugin
      //  * function
      //    any predicate that takes an instance of html-webpack-plugin and returns either
      //    `true` or `false` to control the injection of html metadata for the html files
      //    generated by this instance.
      inject: true,
      // Favicons configuration options (see below)
      favicons: {
        appName: 'YouTravel',
        appDescription: 'YouTravel',
        developerName: 'Cosmin Cojocar',
        developerURL: 'https://cosmin.dev',
        background: '#ffffff',
        theme_color: '#da532c',
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          windows: true,
          yandex: false,
        },
      },
    }),
    new WorkboxWebpackPlugin.InjectManifest({
      swDest: 'sw.js',
      swSrc: './src/client/sw.js',
    }),
  ],
};
